### ISSUE TITLE
VideoWriter cannot write file

### ISSUE THREAD

**Issue by agiantwhale** [aizvorski/scikit-video#2]
```
(env)jae@tesla ~/D/s/s/examples> python test_writer.py test_video 1280 720
Traceback (most recent call last):
  File "test_writer.py", line 21, in <module>
    wr.open()
  File "/home/jae/Development/pigeon/env/local/lib/python2.7/site-packages/skvideo/io/__init__.py", line 150, in open
    self.proc = subprocess.Popen(cmd, stdin=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by aizvorski** [comment]
skimage uses avconv for video I/O. Please try installing avconv (and make sure it is in your path).

On Ubuntu:
sudo apt-get install libav-tools

On other linux: get from http://johnvansickle.com/libav/ unpack and put in path

ffmpeg may work as well but is untested (change avconv/avprobe to ffmpeg/ffprobe in  skvideo/io/__init__py source)

**Comment by agiantwhale** [comment]
Confirmed. Thank you.
